### ISSUE TITLE
Map with many hash collisions crashes with assertion error

### ISSUE THREAD

**Issue by dwightguth** [arximboldi/immer#134]
```
#include <immer/map.hpp>

class KElem {
public:
  KElem(int * elem) {
    this->elem = elem;
  }

  bool operator==(const KElem& other) const {
    return this->elem == other.elem;
  }

  bool operator!=(const KElem& other) const {
    return !(*this == other);
  }

  int * elem;
};

struct HashBlock {
  size_t operator()(const KElem &block) const noexcept {
    return (uintptr_t)block.elem & 0xffffffff00000000;
  }
};


using map = immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>>;

int main() {
    int a[100];
    map m;
    for (int i = 0; i < 100; i++) {
      m = m.set(KElem(a+i), KElem(a+i));
    }
}

```

This program I would expect to either succeed, or, failing that, raise an exception, but instead it crashes with an assertion error and calls abort.

Essentially, what is happening here is we have a bunch of map keys that all have the same hash code. Obviously in practice this indicates that the hash algorithm is bad (and this one in particular is horrible), but the manner of failure here is unfortunate. I would rather it explicitly silently degrade performance, or else, if the data structure library being used is simply incompatible with this many simultaneous collisions, that this be documented somewhere and a friendly error message pointing the user to documentation occur, so that the error is easier to track down for others.

**Comment by arximboldi** [comment]
Hi!

Thanks a lot for the report. The data-structure is meant to work properly with hash collisions, and there are unit tests that specifically check that, but there of course may still be unnoticed bugs, so I'll fix this ASAP.

In order to investigate this it would help: can you tell me which specific assertion fails? 

Thanks!

**Comment by dwightguth** [comment]
```
a.out: /home/dwightguth/llvm-backend/deps/immer/immer/detail/hamts/node.hpp:274: static immer::detail::hamts::node<T, Hash, Equal, MemoryPolicy, B>::node_t* immer::detail::hamts::node<T, Hash, Equal, MemoryPolicy, B>::make_collision_n(immer::detail::hamts::count_t) [with T = std::pair<KElem, KElem>; Hash = immer::map<KElem, KElem, HashBlock, std::equal_to<KElem> >::hash_key; Equal = immer::map<KElem, KElem, HashBlock, std::equal_to<KElem> >::equal_key; MemoryPolicy = immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>; unsigned int B = 5; immer::detail::hamts::node<T, Hash, Equal, MemoryPolicy, B>::node_t = immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem> >::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem> >::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>, 5>; immer::detail::hamts::count_t = unsigned int]: Assertion `n <= branches<B>' failed.
```

**Comment by dwightguth** [comment]
Stack trace in gdb:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7483801 in __GI_abort () at abort.c:79
#2  0x00007ffff747339a in __assert_fail_base (fmt=0x7ffff75fa7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x555555557d3d "n <= branches<B>", file=file@entry=0x555555557cf8 "/home/dwightguth/llvm-backend/deps/immer/immer/detail/hamts/node.hpp", line=line@entry=274, function=function@entry=0x555555559a60 <immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::make_collision_n(unsigned int)::__PRETTY_FUNCTION__> "static immer::detail::hamts::node<T, Hash, Equal, MemoryPolicy, B>::node_t* immer::detail::hamts::node<T, Hash, Equal, MemoryPolicy, B>::make_collision_n(immer::detail::hamts::count_t) [with T = std::"...) at assert.c:92
#3  0x00007ffff7473412 in __GI___assert_fail (assertion=0x555555557d3d "n <= branches<B>", file=0x555555557cf8 "/home/dwightguth/llvm-backend/deps/immer/immer/detail/hamts/node.hpp", line=274, function=0x555555559a60 <immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::make_collision_n(unsigned int)::__PRETTY_FUNCTION__> "static immer::detail::hamts::node<T, Hash, Equal, MemoryPolicy, B>::node_t* immer::detail::hamts::node<T, Hash, Equal, MemoryPolicy, B>::make_collision_n(immer::detail::hamts::count_t) [with T = std::"...) at assert.c:101
#4  0x00005555555571a3 in immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::make_collision_n(unsigned int) ()
#5  0x000055555555630c in immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::copy_collision_insert(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>) ()
#6  0x0000555555555962 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#7  0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#8  0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#9  0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#10 0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#11 0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#12 0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#13 0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#14 0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#15 0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#16 0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#17 0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#18 0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#19 0x0000555555555a67 in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::do_add(immer::detail::hamts::node<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>*, std::pair<KElem, KElem>, unsigned long, unsigned int) const ()
#20 0x000055555555540b in immer::detail::hamts::champ<std::pair<KElem, KElem>, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::hash_key, immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::equal_key, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::add(std::pair<KElem, KElem>) const ()
#21 0x00005555555550cd in immer::map<KElem, KElem, HashBlock, std::equal_to<KElem>, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024ul>, immer::refcount_policy, immer::no_transience_policy, false, true>, 5u>::set(KElem, KElem) const ()
#22 0x0000555555554c27 in main ()
```

**Comment by arximboldi** [comment]
Ok, after looking at it, I think that assertion is safe to remove. You can give it a try in your codebase. You may need to change the memory policy as well though.

**Comment by dwightguth** [comment]
I can confirm that there does not seem to be any difficulty in my larger example when assertions are disabled. The memory policy I mentioned in this example is not my real memory policy; I was simplifying it in order to make the example more straightforward.

Do you plan to make a PR to remove that assertion, if it's actually safe to remove, or should I make one? It would be nice not to have this crash when we build our tool in debug mode.

**Comment by arximboldi** [comment]
Just made a PR fixing this. Thanks for the report @dwightguth !
